name: maggo
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:

  flutter:
    sdk: flutter
  google_fonts:

  cupertino_icons: ^1.0.6
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/nichijou-principal.gif
    - assets/data.csv